FROM rocker/r-bspm:22.04
WORKDIR .
RUN apt-get update && \
  apt-get install -y libxml2-dev

COPY ./requirements-bin.txt .
RUN cat requirements-bin.txt | xargs apt-get install -y -qq

# Install remaining packages from source
#COPY ./requirements-src.R .
#RUN Rscript requirements-src.R

# Clean up package registry
RUN rm -rf /var/lib/apt/lists/*

COPY . . 



EXPOSE 6789
ENTRYPOINT ["R", "-e", "plumber::plumb('scripts/main.R')$run(host = '0.0.0.0', port = 6789, swagger = TRUE)"]"